services:
    nest:
        env_file:
            - selected.env
        image: vuongsyhanh/selected
        command: sh -c "yarn start"
        ports:
            - 3000:3000
        networks:
            - selected
    mongo:
        env_file:
            - selected.env
        image: mongo:focal
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data/mongo:/data/db
        networks:
            - selected
networks:
    selected:
